name: Pharmacie-De-Garde-API

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
  buildAndDeploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: set SHORT_SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: builing the UI
        working-directory: ./client
        env:
          CI: false
          REACT_APP_GITHUB_SHA: ${SHORT_SHA}
        run: |
          yarn install
          yarn build --if-present
      - name: update gitignore
        run: |
          git add -f ./client/build
          git commit -m 'add build to git'
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "frozen-earth-99544"
          heroku_email: ${{secrets.ADMIN_EMAIL}}